# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='District',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='performance',
            old_name='DistrictID',
            new_name='district_id',
        ),
        migrations.RenameField(
            model_name='performance',
            old_name='GradeLevel',
            new_name='grade_level',
        ),
        migrations.RenameField(
            model_name='performance',
            old_name='ParticipationRate2014to2015',
            new_name='participation_rate_2014_to_2015',
        ),
        migrations.RenameField(
            model_name='performance',
            old_name='PercentageMeetsORExceeds2014to2015',
            new_name='percentage_meets_or_exceeds_2014_to_2015',
        ),
        migrations.RenameField(
            model_name='performance',
            old_name='School',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='performance',
            old_name='SchoolID',
            new_name='school_id',
        ),
        migrations.RenameField(
            model_name='performance',
            old_name='Subgroup',
            new_name='subgroup',
        ),
        migrations.RenameField(
            model_name='performance',
            old_name='Subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='DistID',
            new_name='dist_id',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='District',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='School',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='SchoolID',
            new_name='school_id',
        ),
    ]
