# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_data', '0002_auto_20161117_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='academic_year',
            field=models.IntegerField(default=1900),
            preserve_default=False,
        ),
    ]
