# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_data', '0003_performance_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='participation_rate_2014_to_2015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='percentage_meets_or_exceeds_2014_to_2015',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
